#!/usr/bin/env bash
#Controller cron job for muffinMare
BINDIR=$(dirname "$(readlink -fn "$0")")
cd "$BINDIR"
if [ $((`date +%s`-`stat -c %Y pidt`)) -gt 500 ]
   then kill `cat pidt`
   stat -c %Y pidt >> crateLog
fi
